### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by jareth23620149** [SistemasTecTlaxiaco/infografia-jareth23620149#2]
[sistemas numericos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-jareth23620149/files/12501884/sistemas.numericos.pdf)

**Comment by 00Asaf00** [comment]
> [sistemas numericos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-jareth23620149/files/12501884/sistemas.numericos.pdf)
> 

Redacción y Ortografía: 100%
Exposición de Ideas centrales: 50%
Organización de la información: 25%
Uso de imágenes y colores: 40%
Presentación visual: 35%
Referencias: 80%
Presentación: 20%

Calificación: 0.2*50 = 10

**Comment by josealfredo79** [comment]
@00Asaf00 hace falta la calificación no mayor de 20

**Comment by josealfredo79** [comment]
Revisado...
